export const organizations = [
  "Abu Ali ibn Sino nomidagi jamoa salomatligi tibbiyot texnikumi",
  "Amudaryo sohili sport sog'lomlashtirish markazi hududlarini obodonlashtirish dep.",
  "ATB Agrobank hududiy filiali",
  "AT Mikrokreditbank hududiy filiali",
  "BIO TEXNO EKO MChJ Termiz shahar filiali",
  "Budgetdan tashqari Pensiya jamg'armasi Termiz shahar bo'limi",
  "Ekologiya va atrof-muhitni muhofaza qilish bo'yicha Termiz shahar inspeksiyasi",
  "Iqtisodiy jinoyatlarga qarshi kurashish departamenti Termiz shahar bo'limi",
  "Janubgazta'minot UK Termizshahargaz filiali",
  "Kadastr agentligi Davlat kadastrlari palatasi Termiz shahar filiali",
  "Ma'naviyat va ma'rifat markazi Termiz shahar bo'limi",
  "Majburiy ijro byurosi Termiz shahar bo'limi",
  "Nuroniy jamg'armasi Termiz shahar bo'limi",
  "O'zbekiston Adolat SDP Termiz shahar kengashi",
  "O'zbekiston Ekologik partiyasi Termiz shahar tashkiloti",
  "O'zbekiston ko'zi ojizlar jamiyati",
  "O'zbekiston Mahallalar uyushmasi Termiz shahar bo'limi",
  "O'zbekiston Qizil Yarim Oy jamiyati Termiz shahar tashkiloti",
  "O'zbekiston Respublikasi Milliy gvardiyasi Termiz shahar bo'limi",
  "O'zbekiston XDP Termiz shahar kengashi",
  "O'zLiDeP Termiz shahar kengashi",
  "Qishloq xo'jaligi boshqarmasi Termiz shahar bo'limi",
  "San'at saroyi hududi va Xotira maydoni ni obodonlashtirish dep.",
  "Shahar Iqtisodiyot va moliya bo'limi",
  "Shahar Prokuraturasi",
  "Surxondaryo arxitektura va qurilish",
  "Surxondaryo viloyati yuridik texnikumi",
  "Ta'lim va fan xodimlari kasaba uyushmasi Termiz shahar bo'linmasi",
  "Termiz davlat universiteti akademik litseyi",
  "Termiz ixtisoslashgan san'at maktabi",
  "Termiz kasb-hunar maktabi",
  "Termiz muhandislik-texnologiya instituti akademik litseyi",
  "Termiz olimpiya va paralimpiya sport turlariga tayyorlash markazi",
  "Termiz shahar adliya bo'limi",
  "Termiz shahar bo'yicha G'aznachilik bo'linmasi",
  "Termiz shahar Bolalar va o'smirlar sport maktabi",
  "Termiz shahar Davlat veterinariya va chorvachilikni rivojlantirish bo'limi",
  "Termiz shahar Dehqon oziq-ovqat bozori MChJ",
  "Termiz shahar elektr ta'minoti korxonasi",
  "Termiz shahar energiya sotish bo'limi",
  "Termiz shahar Favqulodda vaziyatlar bo'limi",
  "Termiz shahar ichki ishlar boshqarmasi",
  "Termiz shahar Kamba-g'allikni qisqartirish va bandlik bo'limi",
  "Termiz shahar madaniyat bo'limi",
  "Termiz shahar Mudofaa ishlari bo'limi",
  "Termiz shahar nogironlar jamiyati",
  "Termiz shahar Obodonlashtirish boshqarmasi",
  "Termiz shahar qurilish va uy-joy kommunal xo'jaligi bo'limi",
  "Termiz shahar Sanitariya-epidemiologik osoyishtalik bo'limi",
  "Termiz shahar shaxsiy tarkib hujjatlari arxivi",
  "Termiz shahar soliq inspeksiyasi",
  "Termiz shahar statistika bo'limi",
  "Termiz shahar suv ta'minoti bo'limi",
  "Termiz shahar tibbiyot birlashmasi",
  "Termiz shahar xalq ta'limi bo'limi",
  "Termiz-Baktriya-Savdo savdo kompleksi MChJ",
  "Termiz oqshomi gazetasi",
  "Termiz shahridagi Inson ijtimoiy xizmatlari markazi",
  "TIF Milliybank Termiz shahar filiali",
  "Xalq deputatlari Termiz shahar kengashi",
  "Yashil dunyo markaziy dehqon oziq-ovqat bozori MChJ",
  "Yoshlar ishlari agentligi Termiz shahar bo'limi",
].sort((a, b) => a.localeCompare(b, 'uz'));
